# Generated by Django 6.0.5 on 2026-05-27 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('raw_value', models.FloatField()),
                ('normalized_value', models.FloatField(blank=True, null=True)),
                ('raw_unit', models.CharField(max_length=50)),
                ('normalized_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('reporting_date', models.DateField()),
                ('is_suspicious', models.BooleanField(default=False)),
                ('suspicious_reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emissions', to='emissions.company')),
            ],
        ),
    ]
